export interface BibleEditionData {
  title: string;
  slug: string;
  translation: string;
  publisher: string | null;
  publishedYear: number | null;
  description: string;
  history: string;
  canonRating: number;
  canonNotes: string;
  gradientFrom: string;
  gradientTo: string;
  accentColor: string;
  featured: boolean;
  filename: string;
}

// ── Translation family defaults ────────────────────────────────────────────────
const KJV_DEFAULTS = {
  translation: "KJV",
  publisher: "Various Publishers",
  publishedYear: 1611,
  history: "The King James Version was commissioned in 1604 by King James I of England following the Hampton Court Conference. Forty-seven scholars working in six groups across Westminster, Oxford, and Cambridge completed it in 1611. Drawing from the Textus Receptus Greek manuscripts, the Masoretic Hebrew text, and earlier English translations, it became the dominant English Bible for over three centuries. Its majestic prose has profoundly shaped English literature and Western culture.",
  description: "The King James Version is the historic English Bible first published in 1611, renowned for its poetic language and literary influence. One of the most widely printed books in history, it remains a standard of beauty, reverence, and precise scholarship for millions of believers worldwide.",
  canonRating: 10,
  canonNotes: "Strictly 66 books, translated with formal equivalence from the Textus Receptus (NT) and Masoretic Text (OT). Represents the full Protestant canon without addition or omission.",
  gradientFrom: "#1B2A4A", gradientTo: "#0D1525", accentColor: "#C9A84C",
};

const NIV_DEFAULTS = {
  translation: "NIV",
  publisher: "Zondervan / Biblica",
  publishedYear: 1978,
  history: "The New International Version arose from a 1965 initiative by evangelical scholars who sought a contemporary English translation that combined accuracy with readability. The New Testament appeared in 1973, the complete Bible in 1978, revised in 1984 and 2011. Owned by Biblica and published by Zondervan, the NIV uses dynamic equivalence philosophy—conveying the thought rather than just the words of the original. It became the world's best-selling modern Bible translation.",
  description: "The New International Version is the world's most widely read modern Bible, known for its balance of accuracy and contemporary readability. Developed by a team of over 100 scholars from many denominations, it serves as an excellent primary reading Bible for individuals, families, and churches.",
  canonRating: 9,
  canonNotes: "Contains the standard 66-book Protestant canon using dynamic equivalence. Reliable across all major doctrines though some formal precision is traded for readability.",
  gradientFrom: "#1A3320", gradientTo: "#0D1910", accentColor: "#6EAB47",
};

const NASB_DEFAULTS = {
  translation: "NASB",
  publisher: "Lockman Foundation",
  publishedYear: 1971,
  history: "The New American Standard Bible was produced by the Lockman Foundation, completed in 1971 as an update to the American Standard Version of 1901. Scholars sought formal equivalence with updated language. The NASB 1995 update refined readability; the NASB 2020 further updated language while retaining literal precision. Widely regarded as the most accurate English translation available, it is favored by seminaries and Bible scholars worldwide.",
  description: "The New American Standard Bible is prized as the most accurate and literal English translation available. Developed by Lockman Foundation scholars committed to formal equivalence, it precisely renders every word of the Hebrew and Greek text, making it indispensable for serious study.",
  canonRating: 10,
  canonNotes: "Strictly 66 books with formal equivalence translation philosophy. Widely considered the gold standard for accuracy among English translations.",
  gradientFrom: "#3D1515", gradientTo: "#1F0B0B", accentColor: "#D4A574",
};

const NKJV_DEFAULTS = {
  translation: "NKJV",
  publisher: "Thomas Nelson",
  publishedYear: 1982,
  history: "The New King James Version was published in 1982 by Thomas Nelson, representing a seven-year project involving 130 scholars. The NKJV preserves the classic text of the KJV—including its Textus Receptus and Masoretic text base—while updating archaic pronouns (thee, thou) and Early Modern English forms to contemporary language. Footnotes indicate differences from the critical text and the Majority Text, making it useful for textual comparison.",
  description: "The New King James Version preserves the beauty and textual tradition of the 1611 KJV while updating language to modern English. It retains the same Textus Receptus base text as the original King James, making it a trusted choice for those who value both readability and traditional textual scholarship.",
  canonRating: 10,
  canonNotes: "Strictly 66 books using the same Textus Receptus/Masoretic Text base as the KJV with formal equivalence. Full canonical alignment with the Protestant Bible.",
  gradientFrom: "#2A1250", gradientTo: "#150A28", accentColor: "#D4AF37",
};

const ESV_DEFAULTS = {
  translation: "ESV",
  publisher: "Crossway",
  publishedYear: 2001,
  history: "The English Standard Version was published in 2001 by Crossway, under the editorial oversight of J.I. Packer, building on the Revised Standard Version (1971). Scholars from over 50 evangelical denominations created an 'essentially literal' translation that reads naturally in contemporary English. The ESV has been widely adopted in Reformed and evangelical churches. It underwent revisions in 2007, 2011, and a permanent text was established in 2016.",
  description: "The English Standard Version is an essentially literal translation prized for its precision, literary quality, and theological depth. Widely adopted in Reformed and evangelical churches, it serves equally well for public reading, personal devotion, and serious Scripture study.",
  canonRating: 10,
  canonNotes: "Strictly 66 books with essentially literal (formal equivalence) philosophy. Strong alignment with the Hebrew and Greek originals.",
  gradientFrom: "#1E2535", gradientTo: "#0F121A", accentColor: "#5B9EC9",
};

const NLT_DEFAULTS = {
  translation: "NLT",
  publisher: "Tyndale House Publishers",
  publishedYear: 1996,
  history: "The New Living Translation was first published in 1996 by Tyndale House, growing out of a revision of Ken Taylor's Living Bible paraphrase. Over 90 scholars used a 'thought-for-thought' philosophy to create clear, natural English that captures the meaning of the original. Updated in 2004 and 2007, the NLT is particularly popular for devotional reading, children's ministry, and new believers.",
  description: "The New Living Translation renders biblical meaning in clear, contemporary English using a thought-for-thought approach. Ideal for devotional reading and those new to Bible study, it communicates Scripture naturally without sacrificing the integrity of the original message.",
  canonRating: 8,
  canonNotes: "Contains the standard 66-book Protestant canon. The thought-for-thought philosophy introduces interpretive choices, slightly reducing word-level precision.",
  gradientFrom: "#3A2010", gradientTo: "#1C0F08", accentColor: "#E8833A",
};

const CSB_DEFAULTS = {
  translation: "CSB",
  publisher: "Holman Bible Publishers / LifeWay",
  publishedYear: 2017,
  history: "The Christian Standard Bible was published in 2017 by Holman Bible Publishers as a comprehensive revision of the Holman Christian Standard Bible (HCSB, 1999–2004). The HCSB emerged from LifeWay Christian Resources' desire for a translation balancing accuracy with readability using 'optimal equivalence.' The CSB revision involved over 100 scholars from 17 denominations. It is known for rendering the divine name as 'Yahweh' and for high-quality scholarly standards.",
  description: "The Christian Standard Bible uses 'optimal equivalence' to balance word-for-word accuracy with natural, readable English. The product of over 100 scholars from 17 denominations, it is trusted in Baptist, evangelical, and broader conservative church settings.",
  canonRating: 9,
  canonNotes: "Strictly 66 books with optimal equivalence. Highly reliable translation with strong formal accuracy while remaining accessible.",
  gradientFrom: "#0D2B2B", gradientTo: "#061515", accentColor: "#4EC9C0",
};

const NRSV_DEFAULTS = {
  translation: "NRSV",
  publisher: "National Council of Churches",
  publishedYear: 1989,
  history: "The New Revised Standard Version was published in 1989 by the Division of Christian Education of the National Council of Churches, as a thorough revision of the RSV (1952). It was the first major Protestant translation to use consistent gender-inclusive language for human references. The NRSV became the translation of choice for many mainline denominations, Catholic institutions, and academic settings. A further revision, the NRSVue, appeared in 2021.",
  description: "The New Revised Standard Version is the gold standard for academic biblical scholarship and is widely used in mainline Protestant and Catholic institutions. Its gender-inclusive language and rigorous scholarship make it the preferred translation for seminaries, colleges, and ecumenical study.",
  canonRating: 6,
  canonNotes: "Many NRSV editions include the Apocrypha/deuterocanonical books, departing from the strict 66-book Protestant canon. The base 66-book text is accurate, but inclusion of additional books reduces the Protestant canon score.",
  gradientFrom: "#2B1E10", gradientTo: "#150F08", accentColor: "#C9A87E",
};

const AMP_DEFAULTS = {
  translation: "AMP",
  publisher: "Lockman Foundation / Zondervan",
  publishedYear: 1965,
  history: "The Amplified Bible was first published in 1965 by the Lockman Foundation (partnered with Zondervan), with a fully revised edition in 2015. Its distinctive feature is the use of brackets and parentheses to amplify words, showing the full range of meanings behind key Hebrew and Greek terms. Frances Siewert was the primary translator of the original. It draws from the American Standard Version and numerous sources to provide a devotional reading experience that incorporates lexical commentary within the text.",
  description: "The Amplified Bible expands key words with bracketed synonyms drawn from the original languages, giving readers access to the full depth of biblical vocabulary. An unparalleled tool for devotional study and understanding the richness of Hebrew and Greek without needing specialized training.",
  canonRating: 9,
  canonNotes: "Strictly 66 books. The amplification brackets add interpretive notes drawn from lexicons but do not add content beyond what the original languages support.",
  gradientFrom: "#0F1E40", gradientTo: "#070F1F", accentColor: "#E8CC4A",
};

const NIRV_DEFAULTS = {
  translation: "NIrV",
  publisher: "Zondervan",
  publishedYear: 1996,
  history: "The New International Reader's Version was first published in 1996 by Zondervan as a simplified version of the NIV designed for early readers, people with limited reading ability, and English-language learners. Written at roughly a 3rd-grade reading level with shorter sentences and simpler vocabulary, the NIrV is widely used in children's ministry. It follows the same dynamic equivalence philosophy as the NIV.",
  description: "The New International Reader's Version simplifies the NIV to a 3rd-grade reading level, making Scripture accessible to children, new readers, and English learners. A foundational tool for children's ministry and Bible introduction programs.",
  canonRating: 8,
  canonNotes: "Contains the standard 66-book Protestant canon. Simplified language introduces some reduction in precision compared to the base NIV.",
  gradientFrom: "#1A3A60", gradientTo: "#0D1C30", accentColor: "#68B8E8",
};

const HCSB_DEFAULTS = {
  translation: "HCSB",
  publisher: "Holman Bible Publishers",
  publishedYear: 1999,
  history: "The Holman Christian Standard Bible was developed from 1998–2004 by Holman Bible Publishers (LifeWay Christian Resources). It pioneered 'optimal equivalence,' a translation philosophy balancing formal and dynamic approaches more precisely than either the NIV or NASB alone. Uniquely, it rendered the divine name as 'Yahweh' throughout the Old Testament. In 2017 the HCSB was thoroughly revised and renamed the Christian Standard Bible (CSB).",
  description: "The Holman Christian Standard Bible pioneered 'optimal equivalence' — a rigorous balance between word-for-word accuracy and natural English readability. Predecessor to the CSB, it is respected for its scholarship and unique rendering of the divine name Yahweh.",
  canonRating: 9,
  canonNotes: "Strictly 66 books with optimal equivalence. Very high canonical and textual fidelity.",
  gradientFrom: "#0D2B2B", gradientTo: "#061515", accentColor: "#4EC9C0",
};

const OTHER_DEFAULTS = {
  translation: "OTHER",
  publisher: null,
  publishedYear: null,
  history: "This volume is a Bible reference resource, commentary, concordance, or study companion rather than a standalone Bible translation. It draws on multiple translations and scholarly sources to provide insight, background, and tools for deeper engagement with Scripture.",
  description: "A scholarly Bible reference resource providing commentary, background, concordance, or devotional content to complement and deepen Bible study. An invaluable companion to the Scriptures themselves.",
  canonRating: 9,
  canonNotes: "Reference work based on the standard Protestant canon. Not a translation; canon proximity reflects the underlying biblical text used.",
  gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
};

// ── Entry helper ────────────────────────────────────────────────────────────────
type Defaults = Omit<BibleEditionData, "title" | "slug" | "filename" | "featured">;

function e(
  defaults: Defaults,
  title: string,
  slug: string,
  filename: string,
  featured = false,
  overrides: Partial<BibleEditionData> = {}
): BibleEditionData {
  return { ...defaults, title, slug, filename, featured, ...overrides };
}

// ── Full dataset ────────────────────────────────────────────────────────────────
export const BIBLE_EDITIONS: BibleEditionData[] = [
  // ── KJV ──────────────────────────────────────────────────────────────────────
  e(KJV_DEFAULTS, "KJV Study Bible", "kjv-study-bible", "KJV, Study Bible.pdf", true,
    { description: "The KJV Study Bible combines the timeless 1611 King James text with comprehensive study notes, cross-references, and introductions to each book. A definitive reference for anyone committed to the Authorized Version." }),
  e(KJV_DEFAULTS, "KJV the King James Study Bible, Full-Color", "kjv-king-james-study-bible-full-color", "KJV, the King James Study Bible, Full-Color.pdf", true,
    { publisher: "Thomas Nelson", description: "A full-color edition of the King James Study Bible featuring maps, charts, and vibrant design alongside the complete KJV text and exhaustive study apparatus." }),
  e(KJV_DEFAULTS, "KJV Life Application Study Bible", "kjv-life-application-study-bible", "KJV, Life Application Study Bible.pdf", true,
    { publisher: "Tyndale House / Zondervan", description: "The beloved Life Application Study Bible featuring the KJV text, with over 10,000 application notes connecting ancient Scripture to everyday modern life." }),
  e(KJV_DEFAULTS, "KJV Chronological Life Application Study Bible", "kjv-chronological-life-application-study-bible", "KJV, Chronological Life Application Study Bible.pdf", false,
    { description: "A chronological arrangement of the entire KJV text with Life Application notes, allowing readers to experience the Bible in the historical sequence events occurred." }),
  e(KJV_DEFAULTS, "KJV Minister's Bible", "kjv-ministers-bible", "KJV, Minister's Bible.pdf", false,
    { description: "Designed for pastors and ministry leaders, this KJV edition includes funeral, wedding, and ordination services alongside topical outlines and preaching resources." }),
  e(KJV_DEFAULTS, "KJV Word Study Bible, Red Letter", "kjv-word-study-bible-red-letter", "KJV, Word Study Bible, Red Letter.pdf", false,
    { description: "A KJV Bible with embedded Strong's numbers and Hebrew/Greek word studies inline with the text, enabling readers to explore original language meaning without additional reference tools." }),
  e(KJV_DEFAULTS, "KJV Pray the Scriptures Bible, 1st Edition", "kjv-pray-the-scriptures-bible-1st", "KJV, Pray the Scriptures Bible, 1st Edition.pdf", false,
    { description: "Transforms the KJV text into a prayer guide, with prompted applications for turning each passage into personal conversation with God." }),
  e(KJV_DEFAULTS, "KJV Pray the Scriptures Bible, 2nd Edition", "kjv-pray-the-scriptures-bible-2nd", "KJV, Pray the Scriptures Bible, 2nd Edition.pdf", false,
    { description: "The updated second edition of the Pray the Scriptures Bible, with revised prayer prompts and expanded devotional content throughout the KJV text." }),
  e(KJV_DEFAULTS, "KJV Homeschool Mom's Bible", "kjv-homeschool-moms-bible", "KJV, Homeschool Mom's Bible.pdf", false,
    { description: "Crafted for homeschooling mothers, this KJV edition includes devotional notes, teaching helps, and family discipleship guidance integrated throughout Scripture." }),
  e(KJV_DEFAULTS, "KJV Discoverer's Bible", "kjv-discoverers-bible", "KJV, Discoverer's Bible.pdf", false,
    { description: "An adventure-themed KJV Bible for children ages 8–12 with discovery notes, maps, and activities to engage young readers in exploring the Word of God." }),
  e(KJV_DEFAULTS, "KJV Beginner's Bible", "kjv-beginners-bible", "KJV, Beginner's Bible.pdf", false,
    { description: "An introductory KJV Bible designed to help new readers navigate the Scriptures with simple explanations, book introductions, and reading plans." }),
  e(KJV_DEFAULTS, "KJV The Story", "kjv-the-story", "KJV, The Story.pdf", false,
    { description: "The Story presents the KJV Bible as a single, chronological narrative, weaving Old and New Testament passages into a seamless account of God's redemptive plan." }),
  e(KJV_DEFAULTS, "Nelson's Foundational Bible Concordance with KJV", "nelsons-foundational-bible-concordance-kjv", "Nelson's Foundational Bible Concordance with the King James Version Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "A comprehensive topical and word concordance paired with the full KJV text, enabling readers to quickly locate any verse or theme across the entire Bible." }),
  e(KJV_DEFAULTS, "Our Heritage and Faith Bible for African-American Teens, KJV", "our-heritage-faith-bible-teens-kjv", "Our Heritage and Faith Holy Bible for African-American Teens, KJV.pdf", false,
    { description: "A KJV Bible for African-American teenagers featuring devotionals, cultural heritage notes, and reflections celebrating Black Christian history and faith." }),

  // ── NIV ──────────────────────────────────────────────────────────────────────
  e(NIV_DEFAULTS, "NIV Holy Bible", "niv-holy-bible", "NIV, Holy Bible.pdf", true,
    { description: "The standard NIV Holy Bible — the world's best-selling modern translation — combining accuracy and clarity for personal reading, devotion, and church use." }),
  e(NIV_DEFAULTS, "NIV Holy Bible, Red Letter Edition", "niv-holy-bible-red-letter", "NIV, Holy Bible, Red Letter Edition.pdf", true,
    { description: "The complete NIV text with the words of Jesus printed in red, making it easy to locate and meditate on Christ's direct teachings throughout the Gospels and Acts." }),
  e(NIV_DEFAULTS, "NIV Holy Bible, Larger Print", "niv-holy-bible-larger-print", "NIV, The Holy Bible, Larger Print.pdf", false,
    { description: "The complete NIV text in a larger, comfortable font size, ideal for readers who prefer easy-on-the-eye typography without sacrificing portability." }),
  e(NIV_DEFAULTS, "NIV Study Bible, Fully Revised", "niv-study-bible-fully-revised", "NIV, Study Bible, Fully Revised.pdf", true,
    { publisher: "Zondervan", description: "The gold standard NIV Study Bible, fully revised with over 20,000 notes, 100+ charts, 16 pages of full-color maps, and detailed introductions to every book of the Bible." }),
  e(NIV_DEFAULTS, "NIV Zondervan Study Bible", "niv-zondervan-study-bible", "NIV, Zondervan Study Bible.pdf", true,
    { publisher: "Zondervan", description: "A comprehensive study Bible edited by D.A. Carson, featuring notes grounded in biblical theology to help readers see the overarching story of Scripture." }),
  e(NIV_DEFAULTS, "NIV The MacArthur Study Bible", "niv-macarthur-study-bible", "NIV, The MacArthur Study Bible.pdf", true,
    { publisher: "Thomas Nelson", description: "John MacArthur's exhaustive study notes paired with the NIV text, offering verse-by-verse commentary rooted in expository preaching and Reformed theology." }),
  e(NIV_DEFAULTS, "NIV Archaeological Study Bible", "niv-archaeological-study-bible", "NIV, Archaeological Study Bible.pdf", true,
    { publisher: "Zondervan", description: "Combines the NIV text with extensive archaeological discoveries, ancient Near Eastern context, and cultural notes illuminating the world of the biblical writers." }),
  e(NIV_DEFAULTS, "NIV Chronological Study Bible", "niv-chronological-study-bible", "NIV, Chronological Study Bible.pdf", false,
    { description: "Presents the complete NIV text arranged in the historical order events occurred, with cultural and historical notes placing each passage in its proper ancient context." }),
  e(NIV_DEFAULTS, "NIV First-Century Study Bible", "niv-first-century-study-bible", "NIV, First-Century Study Bible.pdf", false,
    { description: "Explores the NIV New Testament against the backdrop of first-century Jewish and Greco-Roman culture, with notes from scholars specializing in the ancient world." }),
  e(NIV_DEFAULTS, "NIV Cultural Backgrounds Study Bible — see NKJV edition", "niv-cultural-backgrounds", "NIV, CoffeeHouse Bible.pdf", false,
    { description: "A culturally focused NIV edition designed for relaxed, conversational engagement with Scripture, featuring accessible notes for modern readers in everyday settings." }),
  e(NIV_DEFAULTS, "NIV Adventure Bible", "niv-adventure-bible", "NIV, Adventure Bible.pdf", false,
    { publisher: "Zondervan", description: "The #1-selling children's Bible in America, featuring the full NIV text alongside adventure-themed notes, character profiles, and activities for ages 8–12." }),
  e(NIV_DEFAULTS, "NIV Kids' Visual Study Bible", "niv-kids-visual-study-bible", "NIV, Kids' Visual Study Bible, Full Color Interior.pdf", false,
    { description: "A visually rich full-color Bible for children featuring infographics, illustrations, maps, and age-appropriate notes alongside the complete NIV text." }),
  e(NIV_DEFAULTS, "NIV Quest Study Bible for Teens", "niv-quest-study-bible-teens", "NIV, Quest Study Bible for Teens.pdf", false,
    { description: "Answers the questions teens actually ask about the Bible, with over 7,000 Q&A notes alongside the NIV text, designed for adolescent inquiry and faith formation." }),
  e(NIV_DEFAULTS, "NIV Teen Study Bible", "niv-teen-study-bible", "NIV, Teen Study Bible.pdf", false,
    { description: "A teen-focused NIV study Bible with notes addressing real-life issues, character profiles, and devotional material relevant to adolescent experience and faith." }),
  e(NIV_DEFAULTS, "NIV Bible for Teen Girls", "niv-bible-teen-girls", "NIV, Bible for Teen Girls.pdf", false,
    { description: "The complete NIV text with devotional notes, Q&A features, and encouragement specifically crafted to speak to teenage girls about faith, identity, and purpose." }),
  e(NIV_DEFAULTS, "NIV True Images Bible", "niv-true-images-bible", "NIV, True Images Bible.pdf", false,
    { description: "A NIV Bible for teen girls addressing real struggles with faith, relationships, and identity through honest devotional notes and real-life stories." }),
  e(NIV_DEFAULTS, "NIV True Images", "niv-true-images", "NIV, True Images.pdf", false,
    { description: "A companion volume to the True Images Bible, featuring devotionals and Scripture passages for teen girls navigating faith in a complex world." }),
  e(NIV_DEFAULTS, "NIV The Woman's Study Bible, Full-Color", "niv-womans-study-bible", "NIV, The Woman's Study Bible, Full-Color.pdf", false,
    { publisher: "Thomas Nelson", description: "A full-color NIV study Bible for women with in-depth notes, character studies of biblical women, and devotional content addressing the female experience of faith." }),
  e(NIV_DEFAULTS, "NIV Young Women of Faith Bible", "niv-young-women-of-faith", "NIV, Young Women of Faith Bible.pdf", false,
    { description: "Designed for young women of faith, this NIV edition features devotional notes and studies focused on character, purity, calling, and growing in God." }),
  e(NIV_DEFAULTS, "NIV Busy Mom's Bible", "niv-busy-moms-bible", "NIV, Busy Mom's Bible.pdf", false,
    { description: "A one-year daily reading NIV Bible offering busy mothers short, focused Scripture readings with brief devotional notes fitting their demanding schedules." }),
  e(NIV_DEFAULTS, "NIV Men's Devotional Bible", "niv-mens-devotional-bible", "NIV, Men's Devotional Bible.pdf", false,
    { description: "A full NIV Bible with devotional readings from well-known Christian men addressing issues of work, integrity, family, and discipleship relevant to modern men." }),
  e(NIV_DEFAULTS, "NIV God's Promises for Men", "niv-gods-promises-for-men", "NIV, God's Promises for Men.pdf", false,
    { description: "A topical NIV Bible collecting God's promises organized around themes central to men's lives: courage, leadership, provision, family, and spiritual strength." }),
  e(NIV_DEFAULTS, "NIV The Maxwell Leadership Bible", "niv-maxwell-leadership-bible", "NIV, The Maxwell Leadership Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "John Maxwell's leadership insights woven throughout the NIV text, identifying and explaining the Bible's 1,600 leadership principles and lessons." }),
  e(NIV_DEFAULTS, "NIV The Charles F. Stanley Life Principles Bible", "niv-stanley-life-principles", "NIV, The Charles F. Stanley Life Principles Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "Dr. Charles Stanley's 30 Life Principles integrated throughout the NIV text as study notes, helping readers apply biblical wisdom to every area of life." }),
  e(NIV_DEFAULTS, "NIV Celebrate Recovery Bible", "niv-celebrate-recovery", "NIV, Celebrate Recovery Bible.pdf", false,
    { description: "Integrates the Celebrate Recovery 12-Step program throughout the NIV text, offering hope and healing to those working through hurts, habits, and hang-ups." }),
  e(NIV_DEFAULTS, "NIV Celebrate Recovery Study Bible", "niv-celebrate-recovery-study", "NIV, Celebrate Recovery Study Bible.pdf", false,
    { description: "A deeper study companion to the Celebrate Recovery Bible, with expanded notes, recovery testimonies, and biblical guidance for addiction and life recovery." }),
  e(NIV_DEFAULTS, "NIV Ragamuffin Bible", "niv-ragamuffin-bible", "NIV, Ragamuffin Bible.pdf", false,
    { description: "Inspired by Brennan Manning's theology of grace, this NIV Bible features notes and devotionals emphasizing God's unconditional love and welcome of broken people." }),
  e(NIV_DEFAULTS, "NIV Encountering God Bible", "niv-encountering-god", "NIV, Encountering God Bible.pdf", false,
    { description: "A NIV Bible designed to cultivate personal encounter with God, with devotional notes encouraging readers to move from information to life-transforming relationship." }),
  e(NIV_DEFAULTS, "NIV Discover God's Heart Devotional Bible", "niv-discover-gods-heart", "NIV, Discover God's Heart Devotional Bible.pdf", false,
    { description: "A devotional NIV Bible helping readers discover God's character and heart throughout all 66 books, tracing His attributes from Genesis to Revelation." }),
  e(NIV_DEFAULTS, "NIV Faith and Work Bible", "niv-faith-and-work", "NIV, Faith and Work Bible.pdf", false,
    { description: "Addresses the integration of Christian faith and vocational life, with notes connecting every passage to themes of work, business, calling, and marketplace ministry." }),
  e(NIV_DEFAULTS, "NIV God's Justice", "niv-gods-justice", "NIV, God's Justice.pdf", false,
    { description: "A thematic NIV Bible focusing on justice, mercy, and care for the vulnerable — exploring what Scripture says about poverty, oppression, and God's call to action." }),
  e(NIV_DEFAULTS, "NIV New Spirit-Filled Life Bible", "niv-new-spirit-filled-life", "NIV, New Spirit-Filled Life Bible.pdf", false,
    { description: "A Charismatic-oriented NIV study Bible edited by Jack Hayford, featuring notes on the Holy Spirit, spiritual gifts, and Spirit-filled Christian living." }),
  e(NIV_DEFAULTS, "NIV Life Journey Bible", "niv-life-journey", "NIV, Life Journey Bible.pdf", false,
    { description: "A NIV Bible organized around life's major transitions and seasons, offering Scripture and devotional notes for every stage of the human journey." }),
  e(NIV_DEFAULTS, "NIV Lifehacks Bible", "niv-lifehacks", "NIV, Lifehacks Bible.pdf", false,
    { description: "A practical NIV Bible with 'lifehack' devotionals connecting biblical truth to everyday productivity, habits, and life skills for modern readers." }),
  e(NIV_DEFAULTS, "NIV The Journey Bible", "niv-the-journey", "NIV, The Journey Bible.pdf", false,
    { description: "Designed for seekers and new believers, The Journey Bible introduces the NIV text with clear notes, background articles, and guided reading plans." }),
  e(NIV_DEFAULTS, "NIV Once-A-Day Bible for Leaders", "niv-once-a-day-leaders", "NIV, Once-A-Day Bible for Leaders.pdf", false,
    { description: "A one-year daily reading NIV Bible tailored for leaders, with leadership-focused devotional notes for each day's reading." }),
  e(NIV_DEFAULTS, "NIV Once-A-Day Bible for Teens", "niv-once-a-day-teens", "NIV, Once-A-Day Bible for Teens.pdf", false,
    { description: "A daily reading NIV Bible for teenagers, guiding teens through the entire Bible in one year with teen-relevant devotional prompts." }),
  e(NIV_DEFAULTS, "NIV Topical Starter Bible", "niv-topical-starter", "NIV, Topical Starter Bible.pdf", false,
    { description: "An introductory topical NIV Bible organizing key passages around major life themes, designed for those beginning their journey with Scripture." }),
  e(NIV_DEFAULTS, "NIV Understand the Faith Study Bible", "niv-understand-the-faith", "NIV, Understand the Faith Study Bible.pdf", false,
    { description: "Systematic theology meets Bible study in this NIV edition that traces core doctrines — Trinity, salvation, church, eschatology — through the complete biblical text." }),
  e(NIV_DEFAULTS, "NIV The Story", "niv-the-story", "NIV, The Story.pdf", false,
    { description: "A chronological narrative Bible presenting the NIV text as a cohesive story, condensed into 31 chapters like a novel to showcase the grand arc of Scripture." }),
  e(NIV_DEFAULTS, "NIV Fruit of the Spirit Bible Collection", "niv-fruit-spirit-collection", "NIV, Fruit of the Spirit Bible Collection.pdf", false,
    { description: "A NIV devotional Bible exploring the nine fruits of the Spirit (Galatians 5:22–23), with notes and applications for cultivating each fruit in daily life." }),
  e(NIV_DEFAULTS, "NIV Armor of God Bible", "niv-armor-of-god", "NIV, Armor of God Bible.pdf", false,
    { description: "Focused on spiritual warfare and Ephesians 6, this NIV Bible helps readers understand and apply the full armor of God in their daily spiritual battles." }),
  e(NIV_DEFAULTS, "NIV The Great Outdoors Bible for Kids", "niv-great-outdoors-kids", "NIV, The Great Outdoors Bible for Kids.pdf", false,
    { description: "An adventure-themed NIV Bible for children connecting Scripture to nature, creation, and outdoor experiences to inspire young explorers of faith." }),
  e(NIV_DEFAULTS, "NIV Wild About Horses Bible", "niv-wild-about-horses", "NIV, Wild About Horses Bible.pdf", false,
    { description: "A NIV Bible for young horse enthusiasts, weaving equestrian themes and devotional notes throughout to connect faith with a passion for horses." }),
  e(NIV_DEFAULTS, "NIV Holman Christian Standard Bible (HCSB)", "bible-hcsb", "Bible, HCSB - Bible.pdf", false,
    { ...HCSB_DEFAULTS, title: "NIV/HCSB Combined Reference Bible", description: "A reference edition combining NIV and HCSB translation features for comparative study." }),
  e(NIV_DEFAULTS, "NIV Celebrate Recovery Bible (Alt. Edition)", "niv-celebrate-recovery-alt", "Bible, NIV Celebrate Recovery B - Bible.pdf", false,
    { description: "An alternate NIV Celebrate Recovery edition with updated recovery testimonies and revised notes for hurts, habits, and hang-ups study." }),
  e(NIV_DEFAULTS, "Our Heritage and Faith Bible for African-American Teens, NIV", "our-heritage-faith-teens-niv", "Our Heritage and Faith Holy Bible for African-American Teens, NIV.pdf", false,
    { description: "A NIV Bible for African-American teenagers with devotionals and cultural heritage notes celebrating Black Christian history and identity." }),
  e(NIV_DEFAULTS, "Rock Solid Faith Study Bible for Teens, NIV", "rock-solid-faith-teens-niv", "Rock Solid Faith Study Bible for Teens, NIV.pdf", false,
    { description: "Helps teens build an unshakeable faith by connecting the NIV text to core doctrines, apologetics, and life application for a skeptical generation." }),

  // ── NASB ─────────────────────────────────────────────────────────────────────
  e(NASB_DEFAULTS, "NASB Bible (with Translator Notes)", "nasb-bible-translator-notes", "Bible, NASB (Includes Translato - Bible.pdf", true,
    { description: "The complete NASB text with the original translator notes from the Lockman Foundation scholars, giving unique insight into the decisions behind the most literal English Bible." }),
  e(NASB_DEFAULTS, "NASB The MacArthur Study Bible", "nasb-macarthur-study-bible", "NASB, The MacArthur Study Bible.pdf", true,
    { publisher: "Thomas Nelson", description: "John MacArthur's comprehensive verse-by-verse study notes paired with the highly literal NASB text — a preeminent resource for serious Bible study and expository preaching." }),
  e(NASB_DEFAULTS, "NASB The Charles F. Stanley Life Principles Bible", "nasb-stanley-life-principles", "NASB, The Charles F. Stanley Life Principles Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "Dr. Charles Stanley's 30 Life Principles integrated throughout the precise NASB text, combining doctrinal accuracy with practical spiritual application." }),

  // ── NKJV ─────────────────────────────────────────────────────────────────────
  e(NKJV_DEFAULTS, "NKJV Study Bible, 2nd Edition", "nkjv-study-bible-2nd", "NKJV, The Study Bible, 2nd Edition.pdf", true,
    { publisher: "Thomas Nelson", description: "The definitive NKJV study Bible with comprehensive notes, book introductions, charts, and maps — updated in its second edition with enhanced study apparatus." }),
  e(NKJV_DEFAULTS, "NKJV MacArthur Study Bible, 2nd Edition", "nkjv-macarthur-study-bible-2nd", "NKJV, MacArthur Study Bible, 2nd Edition.pdf", true,
    { publisher: "Thomas Nelson", description: "John MacArthur's thorough expository study notes in the updated second edition, paired with the traditional NKJV text for word-perfect study." }),
  e(NKJV_DEFAULTS, "NKJV The Vines Expository Bible", "nkjv-vines-expository", "NKJV, The Vines Expository Bible.pdf", true,
    { publisher: "Thomas Nelson", description: "W.E. Vine's classic word study insights embedded throughout the NKJV text, unlocking the Greek and Hebrew meaning of key words for every reader." }),
  e(NKJV_DEFAULTS, "NKJV Cultural Backgrounds Study Bible", "nkjv-cultural-backgrounds", "NKJV, Cultural Backgrounds Study Bible.pdf", false,
    { publisher: "Zondervan", description: "Editors Craig Keener and John Walton illuminate the ancient cultural context of every passage in the NKJV, drawing on archaeology, history, and ancient literature." }),
  e(NKJV_DEFAULTS, "NKJV Chronological Study Bible", "nkjv-chronological-study", "NKJV, Chronological Study Bible.pdf", false,
    { description: "Presents the complete NKJV text in chronological order with historical and cultural notes to help readers understand the biblical narrative in its proper time sequence." }),
  e(NKJV_DEFAULTS, "NKJV Apply the Word Study Bible", "nkjv-apply-the-word", "NKJV, Apply the Word Study Bible.pdf", false,
    { description: "Focuses on practical application, with NKJV study notes designed to help readers move from understanding Scripture to actually living it out each day." }),
  e(NKJV_DEFAULTS, "NKJV Know the Word Study Bible", "nkjv-know-the-word", "NKJV, Know the Word Study Bible.pdf", false,
    { description: "A systematic NKJV study Bible organized to help readers gain a comprehensive grasp of biblical content, themes, and doctrines from Genesis to Revelation." }),
  e(NKJV_DEFAULTS, "NKJV Foundation Study Bible", "nkjv-foundation-study", "NKJV, Foundation Study Bible.pdf", false,
    { description: "A foundational-level NKJV study Bible designed to build solid biblical knowledge for new believers and those seeking a reliable introduction to Scripture." }),
  e(NKJV_DEFAULTS, "NKJV The Open Bible", "nkjv-the-open-bible", "NKJV, The Open Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "A landmark study reference featuring the NKJV text with expanded chain-reference system, survey articles, and comprehensive topical index." }),
  e(NKJV_DEFAULTS, "NKJV Maxwell Leadership Bible", "nkjv-maxwell-leadership", "NKJV, Maxwell Leadership Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "John Maxwell's leadership observations and principles integrated throughout the NKJV text, identifying Scripture's timeless leadership lessons." }),
  e(NKJV_DEFAULTS, "NKJV Maxwell Leadership Bible, 3rd Edition", "nkjv-maxwell-leadership-3rd", "NKJV, Maxwell Leadership Bible, 3rd Edition.pdf", false,
    { publisher: "Thomas Nelson", description: "The updated third edition of Maxwell's leadership Bible with revised notes and expanded leadership insights throughout the NKJV text." }),
  e(NKJV_DEFAULTS, "NKJV The Charles F. Stanley Life Principles Bible", "nkjv-stanley-life-principles", "NKJV, The Charles F. Stanley Life Principles Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "Dr. Stanley's 30 Life Principles presented throughout the NKJV text, offering practical spiritual wisdom anchored in careful biblical exposition." }),
  e(NKJV_DEFAULTS, "NKJV New Spirit-Filled Life Bible", "nkjv-new-spirit-filled-life", "NKJV, New Spirit-Filled Life Bible, 2nd Edition.pdf", false,
    { description: "A Spirit-and-Word study Bible edited by Jack Hayford, combining Charismatic emphasis on the Holy Spirit with the literary quality of the NKJV text." }),
  e(NKJV_DEFAULTS, "NKJV New Spirit-Filled Life Bible, 2nd Edition", "nkjv-new-spirit-filled-life-2nd", "NKJV, New Spirit-Filled Life Bible, 2nd Edition.pdf", false,
    { description: "The revised second edition of the Spirit-Filled Life Bible with updated notes on spiritual gifts, revival, and Holy Spirit ministry in the NKJV." }),
  e(NKJV_DEFAULTS, "NKJV The Modern Life Study Bible", "nkjv-modern-life-study", "NKJV, The Modern Life Study Bible.pdf", false,
    { description: "Bridges the gap between ancient Scripture and modern life with NKJV study notes addressing contemporary issues, culture, and real-world application." }),
  e(NKJV_DEFAULTS, "NKJV Adventure Bible", "nkjv-adventure-bible", "NKJV, Adventure Bible.pdf", false,
    { publisher: "Zondervan", description: "The popular Adventure Bible for children in the NKJV, with the traditional text and exciting notes, maps, and activities for young readers." }),
  e(NKJV_DEFAULTS, "NKJV Airship Genesis Kids Study Bible", "nkjv-airship-genesis-kids", "NKJV, Airship Genesis Kids Study Bible.pdf", false,
    { description: "A children's NKJV Study Bible with an adventure-story framing device, age-appropriate notes, and activities for kids 8–12 exploring the biblical narrative." }),
  e(NKJV_DEFAULTS, "NKJV Ignite — The Bible for Teens", "nkjv-ignite-teens", "NKJV, Ignite - The Bible for Teens.pdf", false,
    { description: "Designed to ignite passionate faith in teenagers, this NKJV Bible features teen-relevant devotionals, Q&A sections, and inspirational notes." }),
  e(NKJV_DEFAULTS, "NKJV American Woman's Bible", "nkjv-american-womans-bible", "NKJV, American Woman's Bible.pdf", false,
    { description: "A NKJV Bible for women featuring profiles of American women of faith, devotional notes, and studies on God's calling for women throughout history." }),
  e(NKJV_DEFAULTS, "NKJV The Story", "nkjv-the-story", "NKJV, The Story.pdf", false,
    { description: "The chronological narrative Bible format in the NKJV, presenting God's story from creation to new creation in a readable, cohesive structure." }),
  e(NKJV_DEFAULTS, "NKJV — Ignite The Bible for Teens (Alt.)", "nkjv-ignite-alt", "Bible, NKJV Ignite_ The Bible f - Bible.pdf", false,
    { description: "An alternate edition of Ignite: The Bible for Teens in the NKJV, with updated content for a new generation of teenage readers." }),
  e(NKJV_DEFAULTS, "NKJV Possessing Your Heart", "nkjv-possessing-your-heart", "Bible, NKJV Possessing Your Hea - Bible.pdf", false,
    { description: "A devotional NKJV Bible focused on the inner life, with meditations for surrendering heart, mind, and will to God's purposes." }),
  e(NKJV_DEFAULTS, "NKJV The Charles F. Stanley Bible (Reference Ed.)", "nkjv-stanley-reference", "Bible, NKJV, The Charles F. Sta - Bible [from Bible, NKJV, The Charles F. Stanley (9825)].pdf", false,
    { publisher: "Thomas Nelson", description: "Reference edition of the Charles F. Stanley Life Principles Bible in NKJV format with comprehensive study notes." }),
  e(NKJV_DEFAULTS, "NKJV The Charles F. Stanley Bible (Standard Ed.)", "nkjv-stanley-standard", "Bible, NKJV, The Charles F. Sta - Bible.pdf", false,
    { publisher: "Thomas Nelson", description: "Standard edition of Dr. Stanley's Life Principles Bible in the NKJV, integrating his teaching ministry with precise biblical text." }),

  // ── ESV ──────────────────────────────────────────────────────────────────────
  e(ESV_DEFAULTS, "ESV The MacArthur Study Bible", "esv-macarthur-study-bible", "ESV, The MacArthur Study Bible.pdf", true,
    { publisher: "Crossway", description: "John MacArthur's definitive verse-by-verse study notes paired with the precise ESV text — an exhaustive reference for expository study and Reformed theology." }),
  e(ESV_DEFAULTS, "ESV Daily Reading Bible", "esv-daily-reading-bible", "ESV, Daily Reading Bible.pdf", false,
    { description: "A one-year daily reading Bible in the ESV, guiding readers through the entire Scripture with morning and evening readings and brief devotional reflections." }),

  // ── NLT ──────────────────────────────────────────────────────────────────────
  e(NLT_DEFAULTS, "NLT The Life Recovery Bible", "nlt-life-recovery", "Bible NLT, The Life Recovery - Bible.pdf", false,
    { publisher: "Tyndale House", description: "Designed for those in recovery, this NLT Bible integrates the 12 Steps and recovery principles throughout Scripture, offering hope for freedom from addiction and brokenness." }),
  e(NLT_DEFAULTS, "NLT New Believer's Bible", "nlt-new-believers", "Bible, NLT, New Believer's Bibl - Bible.pdf", false,
    { publisher: "Tyndale House", description: "An NLT Bible crafted specifically for new Christians, with notes explaining foundational doctrines, Christian growth, and how to live as a follower of Jesus." }),
  e(NLT_DEFAULTS, "NLT Possessing Your Heart", "nlt-possessing-your-heart", "Bible, NLT Possessing Your Heal - Bible.pdf", false,
    { description: "A devotional NLT Bible centered on heart transformation, with meditations on surrendering every aspect of life to God's purposes and presence." }),
  e(NLT_DEFAULTS, "NLT Reign In Life 90-Day Bible", "nlt-reign-in-life-90-day", "Bible, NLT, Reign In Life 90 Da - Bible.pdf", false,
    { description: "A 90-day intensive reading program using the NLT text, designed to take readers through major themes of Scripture in three months of focused engagement." }),
  e(NLT_DEFAULTS, "NLT The One Year Bible", "nlt-one-year-bible", "NLT, The One Year Bible.pdf", false,
    { publisher: "Tyndale House", description: "The classic One Year Bible format in the NLT, offering daily Old Testament, New Testament, Psalm, and Proverb readings to guide readers through the entire Bible in 365 days." }),

  // ── CSB ──────────────────────────────────────────────────────────────────────
  e(CSB_DEFAULTS, "CSB Study Bible", "csb-study-bible", "CSB, Study Bible.pdf", true,
    { description: "The comprehensive CSB Study Bible with over 16,000 study notes, word studies, theological articles, and full-color maps — grounded in the CSB's optimal equivalence." }),
  e(CSB_DEFAULTS, "CSB Every Day with Jesus Daily Bible", "csb-every-day-with-jesus", "CSB, Every Day with Jesus Daily Bible.pdf", false,
    { description: "A one-year daily reading Bible in the CSB featuring devotional notes by Selwyn Hughes from his classic 'Every Day with Jesus' ministry." }),
  e(CSB_DEFAULTS, "CSB The Athlete's Bible (FCA)", "csb-athletes-bible-fca", "CSB, Fellowship of Christian Athletes - The Athlete's Bible.pdf", false,
    { publisher: "Holman / FCA", description: "The official Bible of the Fellowship of Christian Athletes, featuring sports devotionals, athlete testimonies, and the CSB text for competitors of faith." }),
  e(CSB_DEFAULTS, "CSB The Team Bible (FCA)", "csb-team-bible-fca", "CSB, Fellowship of Christian Athletes - The Team Bible.pdf", false,
    { publisher: "Holman / FCA", description: "A team-focused CSB Bible from the Fellowship of Christian Athletes, with devotionals on teamwork, leadership, and competing for Christ." }),
  e(CSB_DEFAULTS, "CSB Heart of God Teen Study Bible", "csb-heart-of-god-teen", "CSB, Heart of God Teen Study Bible.pdf", false,
    { description: "A CSB study Bible for teenagers exploring God's heart revealed throughout Scripture, with teen-relevant notes and devotional content." }),
  e(CSB_DEFAULTS, "Ultimate Bible Atlas — CSB", "csb-ultimate-bible-atlas", "Ultimate Bible Atlas - CSB Bibles by Holman.pdf", false,
    { description: "A comprehensive biblical atlas paired with the CSB, featuring hundreds of full-color maps, photographs, and geographical data illuminating the world of the Bible." }),

  // ── NRSV ─────────────────────────────────────────────────────────────────────
  e(NRSV_DEFAULTS, "NRSV Bible with the Apocrypha", "nrsv-bible-with-apocrypha", "NRSV, Bible with the Apocrypha.pdf", true,
    { description: "The complete NRSV text with the full Apocrypha/deuterocanonical books, the edition most used in academic and ecumenical settings for its breadth and scholarly rigor." }),
  e(NRSV_DEFAULTS, "NRSV HarperCollins Study Bible", "nrsv-harpercollins-study", "NRSV, HarperCollins Study Bible.pdf", true,
    { publisher: "HarperOne / Society of Biblical Literature", description: "The premier academic study Bible, edited by the Society of Biblical Literature with notes by leading biblical scholars covering archaeology, history, and theology." }),
  e(NRSV_DEFAULTS, "NRSV Cultural Backgrounds Study Bible", "nrsv-cultural-backgrounds", "NRSV, Cultural Backgrounds Study Bible.pdf", false,
    { publisher: "Zondervan", description: "Keener and Walton's cultural backgrounds scholarship applied to the NRSV text, illuminating ancient world context for every book of the Bible." }),
  e(NRSV_DEFAULTS, "NRSV The Catholic Faith & Family Bible", "nrsv-catholic-faith-family", "NRSV, The Catholic Faith & Family Bible.pdf", false,
    { canonRating: 5, description: "A Catholic family Bible using the NRSV text with the full Catholic canon, featuring faith formation notes and devotional content for Catholic families." }),
  e(NRSV_DEFAULTS, "NRSV The Daily Bible", "nrsv-daily-bible", "NRSV, The Daily Bible.pdf", false,
    { description: "A one-year chronological reading Bible in the NRSV, designed for daily engagement with the full text of Scripture in historical sequence." }),
  e(NRSV_DEFAULTS, "NRSV The Guidebook", "nrsv-guidebook", "NRSV, the Guidebook.pdf", false,
    { description: "A navigational introduction to the NRSV for those new to the Bible, with guided reading paths, explanations of biblical genres, and orientation notes." }),
  e(NRSV_DEFAULTS, "NRSV Catholic Edition — New Testament", "nrsv-catholic-new-testament", "NRSV Catholic Edition Bible Anglicized - New Testament.pdf", false,
    { canonRating: 5, description: "The New Testament volume of the anglicized NRSV Catholic Edition, featuring the Catholic canonical text with Anglicized spelling for UK and Commonwealth readers." }),
  e(NRSV_DEFAULTS, "NRSV Catholic Edition — Old Testament", "nrsv-catholic-old-testament", "NRSV Catholic Edition Bible Anglicized - Old Testament.pdf", false,
    { canonRating: 5, description: "The Old Testament volume of the anglicized NRSV Catholic Edition, including the deuterocanonical books of the Catholic canon with Anglicized text." }),
  e(NRSV_DEFAULTS, "HarperCollins Study Bible", "harpercollins-study-bible", "Bible, The HarperCollins Study - Bible.pdf", false,
    { publisher: "HarperOne", description: "The Society of Biblical Literature's flagship study Bible featuring the NRSV text and notes from leading academic scholars across all major biblical disciplines." }),

  // ── Amplified ────────────────────────────────────────────────────────────────
  e(AMP_DEFAULTS, "Amplified Bible", "amplified-bible", "Amplified Bible.pdf", true,
    { description: "The original and beloved Amplified Bible, expanding key words with brackets to reveal the full breadth of the Hebrew and Greek originals — a classic devotional study tool." }),
  e(AMP_DEFAULTS, "Amplified Holy Bible", "amplified-holy-bible", "Amplified Holy Bible.pdf", true,
    { description: "The 2015 revised Amplified Holy Bible, offering a fresh update to the classic Amplified text with improved clarity while retaining its signature bracket amplification system." }),
  e(AMP_DEFAULTS, "The Amplified Study Bible", "amplified-study-bible", "The Amplified Study Bible.pdf", true,
    { publisher: "Zondervan", description: "The Amplified text enhanced with comprehensive study notes, character profiles, topical articles, and visual aids for deeper engagement with amplified Scripture." }),
  e(AMP_DEFAULTS, "Amplified Cross-Reference Bible", "amplified-cross-reference", "Amplified Cross-Reference Bible.pdf", false,
    { description: "The Amplified Bible combined with an extensive cross-reference system, enabling readers to trace themes, words, and doctrines across the entire amplified text." }),
  e(AMP_DEFAULTS, "Amplified Cross-Reference Bible (Zondervan Ed.)", "amplified-cross-reference-zondervan", "Amplified Cross-Reference Bible - Zondervan.pdf", false,
    { publisher: "Zondervan", description: "Zondervan's edition of the Amplified Cross-Reference Bible, offering the amplified text with a refined cross-reference apparatus and study features." }),
  e(AMP_DEFAULTS, "Amplified Cross-Reference Bible (Bible Ed.)", "amplified-cross-reference-bible-ed", "Amplified Cross-Reference Bible - Bible.pdf", false,
    { description: "An alternate cross-reference edition of the Amplified Bible with expanded margin notes and biblical cross-references throughout." }),
  e(AMP_DEFAULTS, "Amplified Holy Bible (Captures Edition)", "amplified-holy-bible-captures", "Amplified Holy Bible_ Captures - Bible.pdf", false,
    { description: "A special captures edition of the Amplified Holy Bible with highlighted key passages and thematic groupings for focused study." }),
  e(AMP_DEFAULTS, "AMP Bible (Standard Reference)", "amp-bible-standard", "Bible, AMP, Amplified Bible - Bible.pdf", false,
    { description: "A standard reference edition of the Amplified Bible, the full amplified text without additional study features for straightforward devotional reading." }),
  e(AMP_DEFAULTS, "Amplified Bible (Standard Ed.)", "amplified-bible-standard-ed", "Bible, Amplified Bible - Bible.pdf", false,
    { description: "Standard edition of the Amplified Bible for everyday devotional and study use, preserving the full bracket expansion system throughout the text." }),

  // ── NIrV ─────────────────────────────────────────────────────────────────────
  e(NIRV_DEFAULTS, "NIrV Holy Bible for Adults", "nirv-holy-bible-adults", "NIrV, Holy Bible for Adults.pdf", false,
    { description: "The complete NIrV text in an adult-oriented edition, designed for people with limited reading ability, learning disabilities, or those new to English seeking clear Scripture." }),
  e(NIRV_DEFAULTS, "NIrV Study Bible for Kids", "nirv-study-bible-kids", "NIrV, Study Bible for Kids.pdf", false,
    { description: "A full-featured study Bible for children using the simplified NIrV text with age-appropriate notes, maps, and activities for young Bible explorers." }),
  e(NIRV_DEFAULTS, "NIrV Faith Builders Bible", "nirv-faith-builders", "NIrV, Faith Builders Bible.pdf", false,
    { description: "A NIrV Bible for children with devotionals and activities designed to build strong foundational faith through age-appropriate Scripture engagement." }),
  e(NIRV_DEFAULTS, "NIrV God Watches Over Me Bible", "nirv-god-watches-over-me", "NIrV, God Watches Over Me Bible.pdf", false,
    { description: "A comforting NIrV Bible for young children emphasizing God's care and protection, with simple notes about God's love and faithfulness." }),
  e(NIRV_DEFAULTS, "NIrV Minecrafters Bible", "nirv-minecrafters-bible", "NIrV, Minecrafters Bible.pdf", false,
    { description: "A Minecraft-themed NIrV Bible connecting Scripture to the popular video game world, engaging young gamers with biblical stories through familiar imagery." }),
  e(NIRV_DEFAULTS, "NIrV The Story for Kids", "nirv-the-story-kids", "NIrV, The Story for Kids.pdf", false,
    { description: "The NIrV narrative Bible in a format designed for children, presenting God's story from creation to new creation in simple, engaging language." }),
  e(NIRV_DEFAULTS, "NIrV The Super Heroes Bible", "nirv-super-heroes", "NIrV, The Super Heroes Bible.pdf", false,
    { description: "A superhero-themed NIrV Bible for children presenting biblical heroes of faith alongside their stories in the simplified NIrV text." }),
  e(NIRV_DEFAULTS, "NIrV May the Faith Be with You Holy Bible", "nirv-may-the-faith", "NIrV, May the Faith Be with You Holy Bible.pdf", false,
    { description: "A Star Wars-inspired NIrV Bible for young fans, connecting the themes of spiritual battle, faith, and redemption in Scripture to beloved characters and stories." }),

  // ── Specialty / Independent Translations ─────────────────────────────────────
  {
    title: "A Literary Bible",
    slug: "a-literary-bible",
    translation: "LITERARY",
    publisher: null,
    publishedYear: null,
    description: "A Literary Bible approaches Scripture as a work of literature, highlighting poetry, narrative structure, and rhetorical artistry. Designed for readers who wish to engage the aesthetic and literary dimensions of biblical writing alongside its theological content.",
    history: "Literary Bible translations emphasize the original languages' literary qualities — parallelism in Hebrew poetry, ring composition, chiasm, and narrative artistry. This approach emerged from scholarship recognizing that the Bible's literary form is inseparable from its theological message.",
    canonRating: 9,
    canonNotes: "Based on the standard 66-book Protestant canon with translation emphasis on literary quality.",
    gradientFrom: "#2A2010", gradientTo: "#141008", accentColor: "#C9B870",
    featured: false, filename: "A Literary Bible.pdf",
  },
  {
    title: "Berean Literal Bible (New Testament)",
    slug: "berean-literal-bible-nt",
    translation: "BEREAN",
    publisher: "Bible Hub",
    publishedYear: 2020,
    description: "The Berean Literal Bible renders the Greek New Testament with extreme word-for-word precision, often preserving Greek syntax in English for maximum transparency to the original text. An invaluable tool for word studies and interlinear comparison.",
    history: "The Berean Bible project was developed by Bible Hub beginning around 2016, aiming to provide a freely available, modern literal translation using the best available Greek and Hebrew manuscripts with current scholarship. The Berean Literal Bible prioritizes transparency over readability.",
    canonRating: 10,
    canonNotes: "Strictly the New Testament (27 books) in extreme formal equivalence. Maximum proximity to Greek source text.",
    gradientFrom: "#0F2820", gradientTo: "#081410", accentColor: "#5AC890",
    featured: false, filename: "Berean Literal Bible (New Testa - Bible Hub.pdf",
  },
  {
    title: "Berean Study Bible (New Testament)",
    slug: "berean-study-bible-nt",
    translation: "BEREAN",
    publisher: "Bible Hub",
    publishedYear: 2016,
    description: "The Berean Study Bible balances literal accuracy with natural English readability, making it accessible for both study and devotional reading. Freely available and grounded in modern critical scholarship.",
    history: "Developed alongside the Berean Literal Bible by Bible Hub, the Berean Study Bible (BSB) uses a balanced approach — literal enough for word studies but readable enough for devotional use. It is extensively cross-referenced and publicly available for free.",
    canonRating: 10,
    canonNotes: "New Testament portion strictly follows the 27-book canon with formal equivalence. High textual fidelity.",
    gradientFrom: "#0F2820", gradientTo: "#081410", accentColor: "#5AC890",
    featured: false, filename: "Berean Study Bible (New Testame - Bible Hub.pdf",
  },
  {
    title: "Complete Jewish Bible",
    slug: "complete-jewish-bible",
    translation: "CJB",
    publisher: "Jewish New Testament Publications / Messianic Jewish Publishers",
    publishedYear: 1998,
    description: "The Complete Jewish Bible by David H. Stern presents the entire Bible from a Messianic Jewish perspective, using Hebrew names (Yeshua, Sha'ul) and Jewish cultural terminology throughout. It bridges the Jewishness of Jesus and the early church with contemporary faith.",
    history: "David Stern combined his Jewish New Testament (1989) with a Hebrew Names Version of the Old Testament to produce the Complete Jewish Bible in 1998. Stern, a Messianic Jewish scholar, sought to reclaim the Jewish roots of the Christian faith by restoring the Hebraic character of the text. It contains the 66 books of the Protestant canon arranged in traditional order.",
    canonRating: 7,
    canonNotes: "Contains all 66 Protestant canonical books but uses Hebraic naming conventions and cultural framing that differ from standard translations. Canon content is complete but culturally reoriented.",
    gradientFrom: "#1A2840", gradientTo: "#0D1420", accentColor: "#D4AF37",
    featured: true, filename: "Complete Jewish Bible.pdf",
  },
  {
    title: "Common English Bible with Apocrypha",
    slug: "common-english-bible-apocrypha",
    translation: "CEB",
    publisher: "Common English Bible",
    publishedYear: 2011,
    description: "The Common English Bible offers a contemporary, inclusive translation accessible to a wide range of readers, including the deuterocanonical books. Written at a 7th-grade reading level by over 120 scholars, it serves ecumenical and mainline Christian communities.",
    history: "The CEB was completed in 2011 by a team of over 120 scholars from 22 denominations, sponsored by major mainline Protestant publishers. It prioritizes clear, natural American English with gender-accurate language and is one of the few Protestant-sponsored translations to include the Apocrypha/deuterocanonical books alongside the standard 66 books.",
    canonRating: 6,
    canonNotes: "This edition includes the deuterocanonical/Apocrypha books beyond the 66-book Protestant canon. The base 66-book translation is solid but inclusion of additional books reduces the Protestant canon score.",
    gradientFrom: "#283010", gradientTo: "#141808", accentColor: "#B8C870",
    featured: false, filename: "Common English Bible with Apocr - Bible.pdf",
  },
  {
    title: "Darby Mini Study Bible",
    slug: "darby-mini-study-bible",
    translation: "DARBY",
    publisher: "Various / Public Domain",
    publishedYear: 1890,
    description: "The Darby Bible is one of the most extremely literal English translations ever produced, favored by serious students for its transparency to the Greek and Hebrew. John Nelson Darby's translation influenced dispensationalism and many 20th-century evangelical scholars.",
    history: "John Nelson Darby (1800–1882), an Anglo-Irish Bible teacher and founder of the Plymouth Brethren movement, translated both Testaments from the original languages. His New Testament appeared in 1871, the complete Bible posthumously around 1890. Known for remarkable literalism, it influenced J.N. Darby's dispensational theology and figures like C.I. Scofield.",
    canonRating: 10,
    canonNotes: "Strictly 66 books with extreme formal equivalence from Greek and Hebrew. Very high canonical fidelity.",
    gradientFrom: "#201E1E", gradientTo: "#100F0F", accentColor: "#A8A090",
    featured: false, filename: "Darby Mini Study Bible.pdf",
  },
  {
    title: "Holy Bible, From the Ancient Eastern Text",
    slug: "holy-bible-ancient-eastern-text",
    translation: "PESHITTA",
    publisher: "Harper & Row",
    publishedYear: 1933,
    description: "George Lamsa's translation from the Aramaic Peshitta (rather than Greek and Hebrew) offers a unique perspective on difficult passages, reflecting the Semitic background of Jesus and the early church. A fascinating window into the Eastern Christian tradition.",
    history: "George M. Lamsa (1892–1975), a native Aramaic speaker from Persia, translated the entire Bible from the Syriac Peshitta and published it in 1933. Lamsa believed the Peshitta was the original New Testament text rather than a translation from Greek. While most scholars disagree, his translation illuminates Semitic idioms that clarify many difficult passages.",
    canonRating: 7,
    canonNotes: "Based on the Syriac Peshitta rather than the standard Greek/Hebrew texts, with some differences in book order and textual tradition. Contains the 66 books but from a distinct textual family.",
    gradientFrom: "#2A1E10", gradientTo: "#150F08", accentColor: "#D4A870",
    featured: false, filename: "Holy Bible, From the Ancient Eastern Text.pdf",
  },
  {
    title: "The Passion Translation — New Testament",
    slug: "the-passion-translation-nt",
    translation: "TPT",
    publisher: "BroadStreet Publishing",
    publishedYear: 2017,
    description: "The Passion Translation by Brian Simmons aims to convey the passion and emotion of the New Testament at 'heart level.' Popular in charismatic circles for its vivid language, it has also received significant scholarly criticism for additions beyond the source text.",
    history: "The Passion Translation is the work of Brian Simmons, who began publishing it in 2017 through BroadStreet Publishing. Simmons describes his method as a 'heart-level' translation conveying the passion of the original. Prominent evangelical and Reformed scholars have raised concerns about additions and interpretations not supported by the Greek manuscripts, while charismatic communities have widely embraced it.",
    canonRating: 4,
    canonNotes: "New Testament only. Multiple scholars have documented additions and expansions not supported by the Greek source text, significantly reducing fidelity to the original canonical content.",
    gradientFrom: "#3A0F1F", gradientTo: "#1C080F", accentColor: "#E84878",
    featured: false, filename: "The Passion Translation New Tes - Brian Simmons.pdf",
  },
  {
    title: "The Voice Bible",
    slug: "the-voice-bible",
    translation: "VOICE",
    publisher: "Thomas Nelson / Ecclesia Bible Society",
    publishedYear: 2012,
    description: "The Voice presents Scripture as a dramatic script with dialogue assigned to characters and cultural notes integrated throughout. Created by scholars and creative writers, it prioritizes the literary and narrative experience of reading the Bible.",
    history: "The Voice was produced by the Ecclesia Bible Society in partnership with Thomas Nelson, completing the full Bible in 2012. It pairs biblical scholars with creative writers to render Scripture in a format resembling a screenplay or dramatic narrative. While praised for readability, it takes significant liberty with phrasing for literary effect.",
    canonRating: 7,
    canonNotes: "Contains the standard 66-book Protestant canon. The dramatic script format and creative paraphrase approach introduce interpretive liberty reducing word-level fidelity.",
    gradientFrom: "#1E2A10", gradientTo: "#0F1508", accentColor: "#8AC860",
    featured: false, filename: "The Voice Bible.pdf",
  },
  {
    title: "The Voice, Compass Bible",
    slug: "the-voice-compass-bible",
    translation: "VOICE",
    publisher: "Thomas Nelson / Ecclesia Bible Society",
    publishedYear: 2012,
    description: "The Compass Bible edition of The Voice includes navigational study helps, thematic guides, and orienting notes to help readers find their direction in Scripture using the distinctive Voice translation.",
    history: "The Compass edition extends The Voice Bible's dramatic script format with added directional study tools, designed to help readers navigate Scripture thematically and spiritually. It is part of the broader Voice Bible publishing project.",
    canonRating: 7,
    canonNotes: "Same canonical content and translation philosophy as The Voice Bible — 66 books with creative paraphrase approach.",
    gradientFrom: "#1E2A10", gradientTo: "#0F1508", accentColor: "#8AC860",
    featured: false, filename: "The Voice, Compass Bible.pdf",
  },
  {
    title: "The New American Bible",
    slug: "the-new-american-bible",
    translation: "NAB",
    publisher: "USCCB / Catholic Biblical Association of America",
    publishedYear: 1970,
    description: "The New American Bible is the official Catholic Bible in the United States, used in the Catholic Lectionary and approved by the USCCB. The NABRE (revised edition) features a new Old Testament translation and updated notes reflecting current Catholic biblical scholarship.",
    history: "Produced by the Catholic Biblical Association of America under USCCB sponsorship, the NAB Old Testament appeared in 1970, with NT revisions in 1986 and a full NABRE in 2011. It is a scholarly Catholic translation from the original languages, following the Catholic canon of 73 books including the deuterocanonicals.",
    canonRating: 5,
    canonNotes: "Follows the Catholic canon of 73 books, including 7 deuterocanonical books not in the Protestant canon. For Protestant 66-book canon proximity, the score reflects the additional books.",
    gradientFrom: "#1A0F3A", gradientTo: "#0D0820", accentColor: "#C9A84C",
    featured: false, filename: "The New American Bible.pdf",
  },
  {
    title: "The Revised New Jerusalem Bible",
    slug: "revised-new-jerusalem-bible",
    translation: "RNJB",
    publisher: "Darton, Longman and Todd",
    publishedYear: 2019,
    description: "The Revised New Jerusalem Bible is the latest revision of the scholarly Catholic Jerusalem Bible tradition, featuring a fresh translation by Henry Wansbrough and updated contemporary language. It serves Catholic readers seeking academic rigor and literary quality.",
    history: "The Jerusalem Bible (1966) was a groundbreaking English Catholic translation from original languages, informed by the French Bible de Jérusalem. The New Jerusalem Bible (1985) revised it, and Henry Wansbrough OSB's Revised New Jerusalem Bible (2019) represents the most current update, using the Lectio Divina approach and contemporary inclusive language.",
    canonRating: 5,
    canonNotes: "Follows the Catholic canon of 73 books including deuterocanonicals. Not aligned with the 66-book Protestant canon.",
    gradientFrom: "#2A0F20", gradientTo: "#150810", accentColor: "#C87090",
    featured: false, filename: "The Revised New Jerusalem Bible.pdf",
  },
  {
    title: "The Expanded Bible",
    slug: "the-expanded-bible",
    translation: "EXB",
    publisher: "Thomas Nelson",
    publishedYear: 2011,
    description: "The Expanded Bible embeds translation alternatives, completions of idioms, and clarifying notes directly in brackets throughout the text, giving readers multiple interpretive options within a single reading experience. A unique tool for deeper textual engagement.",
    history: "Developed by Tremper Longman III, Mark Strauss, and Daniel Taylor, the Expanded Bible (2011) builds on the New Century Version base text, expanding it with alternatives drawn from multiple translations and lexicons. The goal is to show the range of possible renderings without requiring the reader to consult multiple Bibles.",
    canonRating: 8,
    canonNotes: "Contains the standard 66-book Protestant canon. The expansion brackets show translation options but do not add non-canonical content.",
    gradientFrom: "#1A2A3A", gradientTo: "#0D151E", accentColor: "#7AB8E8",
    featured: false, filename: "The Expanded Bible.pdf",
  },
  {
    title: "The Kingdom New Testament",
    slug: "the-kingdom-new-testament",
    translation: "KNT",
    publisher: "HarperOne",
    publishedYear: 2011,
    description: "N.T. Wright's fresh New Testament translation brings his deep scholarship to bear on conveying the political, cultural, and theological thrust of the NT in vivid contemporary English. Acclaimed for capturing the urgency and color of the first-century message.",
    history: "N.T. Wright (Tom Wright), one of the foremost New Testament scholars of the modern era, published The Kingdom New Testament in 2011. Drawing on decades of academic work on Jesus, Paul, and the early church, he aims for a translation that captures both the precise meaning and the rhetorical power of the Greek original for modern readers.",
    canonRating: 9,
    canonNotes: "New Testament only (27 books). Scholarly formal-to-dynamic equivalence with high fidelity to the Greek source text.",
    gradientFrom: "#1A2A3A", gradientTo: "#0D151E", accentColor: "#7AB8E8",
    featured: false, filename: "The Kingdom New Testament - A Contemporary Translation.pdf",
  },
  {
    title: "The Apologetics Study Bible",
    slug: "the-apologetics-study-bible",
    translation: "HCSB",
    publisher: "Holman Bible Publishers",
    publishedYear: 2007,
    description: "The Apologetics Study Bible equips believers to defend the faith, featuring the HCSB text alongside notes by leading apologists addressing tough questions about Christianity, science, history, and culture.",
    history: "Published by Holman Bible Publishers in 2007, The Apologetics Study Bible was developed in response to growing atheist and skeptical challenges to Christian faith. It features over 100 articles by respected apologists including Norman Geisler, Ravi Zacharias, and Lee Strobel, alongside the reliable HCSB text.",
    canonRating: 9,
    canonNotes: "Uses the HCSB text — 66-book Protestant canon with optimal equivalence translation philosophy.",
    gradientFrom: "#1A2035", gradientTo: "#0D1019", accentColor: "#7090C8",
    featured: false, filename: "The Apologetics Study Bible.pdf",
  },
  {
    title: "The Apologetics Study Bible — Understand Why You Believe",
    slug: "the-apologetics-study-bible-why-you-believe",
    translation: "HCSB",
    publisher: "Holman Bible Publishers",
    publishedYear: 2012,
    description: "An updated edition of the Apologetics Study Bible with expanded articles and notes focused on helping believers understand and articulate the reasons behind their faith.",
    history: "This expanded edition of the Apologetics Study Bible adds new content specifically addressing why people believe, with testimonies, updated apologetic articles, and enhanced study tools alongside the HCSB text.",
    canonRating: 9,
    canonNotes: "HCSB base text — 66-book Protestant canon with optimal equivalence.",
    gradientFrom: "#1A2035", gradientTo: "#0D1019", accentColor: "#7090C8",
    featured: false, filename: "The Apologetics Study Bible - Understand Why You Believe.pdf",
  },
  {
    title: "The Beginner's Bible",
    slug: "the-beginners-bible",
    translation: "PARAPHRASE",
    publisher: "Zondervan",
    publishedYear: 1989,
    description: "The Beginner's Bible is one of the most beloved children's Bible storybooks, retelling 90 biblical stories in simple language and vibrant illustrations for young children ages 2–6.",
    history: "Published by Zondervan in 1989 with colorful illustrations, The Beginner's Bible has sold over 25 million copies and introduced generations of young children to Bible stories. It is not a full translation but a simplified story Bible presenting key narratives in language accessible to preschoolers.",
    canonRating: 8,
    canonNotes: "Story Bible for young children based on the Protestant canon. Not a full translation but accurately represents key biblical narratives.",
    gradientFrom: "#1A3A5A", gradientTo: "#0D1C2A", accentColor: "#78C8E8",
    featured: false, filename: "The Beginner's Bible.pdf",
  },
  {
    title: "The Berenstain Bears Holy Bible",
    slug: "berenstain-bears-holy-bible",
    translation: "NIrV",
    publisher: "Zondervan",
    publishedYear: 2000,
    description: "A children's Bible featuring the beloved Berenstain Bears characters alongside the NIrV text, connecting popular family characters to Scripture for young readers just beginning their faith journey.",
    history: "Published by Zondervan, this children's Bible combines the simplified NIrV text with Stan and Jan Berenstain's famous bear family characters, who were explicitly Christian in their later works. The Bears serve as a friendly guide helping young readers engage with biblical content.",
    canonRating: 8,
    canonNotes: "Uses the NIrV translation — 66-book Protestant canon in simplified language for children.",
    gradientFrom: "#1A3A60", gradientTo: "#0D1C30", accentColor: "#68B8E8",
    featured: false, filename: "The Berenstain Bears Holy Bible.pdf",
  },
  {
    title: "The Bible Recap",
    slug: "the-bible-recap",
    translation: "OTHER",
    publisher: "Bethany House",
    publishedYear: 2020,
    description: "The Bible Recap by Tara-Leigh Cobble is a popular companion guide to reading the Bible chronologically in one year, with daily summaries and devotional reflections for each day's reading across any translation.",
    history: "Tara-Leigh Cobble developed The Bible Recap from her D-Group (Discipleship Groups) ministry, which later became a podcast followed by millions. The book (2020) accompanies her chronological Bible reading plan, helping readers connect themes and understand the narrative arc of Scripture.",
    canonRating: 9,
    canonNotes: "Reference/companion work based on the complete 66-book Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "The Bible Recap.pdf",
  },
  {
    title: "The Complete Bible Answer Book",
    slug: "the-complete-bible-answer-book",
    translation: "OTHER",
    publisher: "Thomas Nelson",
    publishedYear: 2009,
    description: "Hank Hanegraaff's comprehensive Q&A resource answering over 180 of the most frequently asked questions about the Bible, Christianity, and the Christian life with Scripture references throughout.",
    history: "Published by Thomas Nelson, The Complete Bible Answer Book compiles questions Hank Hanegraaff has addressed over his decades as president of the Christian Research Institute. It serves as an accessible apologetics and biblical reference tool.",
    canonRating: 9,
    canonNotes: "Reference work drawing from the standard 66-book Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "The Complete Bible Answer Book.pdf",
  },
  {
    title: "The Essential Bible Dictionary",
    slug: "the-essential-bible-dictionary",
    translation: "OTHER",
    publisher: "Holman Bible Publishers",
    publishedYear: 2011,
    description: "A concise yet comprehensive Bible dictionary defining key people, places, theological terms, and concepts throughout Scripture, designed for students and general Bible readers.",
    history: "Published by Holman as part of the Holman QuickSource series, The Essential Bible Dictionary provides accessible definitions and explanations for thousands of biblical terms, supporting readers using any translation in their study of Scripture.",
    canonRating: 9,
    canonNotes: "Reference work covering the complete biblical canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "The Essential Bible Dictionary.pdf",
  },
  {
    title: "The IVP Bible Background Commentary",
    slug: "ivp-bible-background-commentary",
    translation: "OTHER",
    publisher: "InterVarsity Press",
    publishedYear: 1993,
    description: "Craig Keener's groundbreaking commentary providing verse-by-verse cultural and historical background for every passage in the New Testament, illuminating the ancient world of the biblical writers.",
    history: "Craig S. Keener published this IVP commentary in 1993 as a layperson-accessible distillation of his extensive scholarship on the Greco-Roman and Jewish backgrounds of the New Testament. It became one of the most useful single-volume Bible background resources available.",
    canonRating: 9,
    canonNotes: "Commentary work on the standard Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "The IVP Bible Background Commentary.pdf",
  },
  {
    title: "The Moody Bible Commentary",
    slug: "the-moody-bible-commentary",
    translation: "OTHER",
    publisher: "Moody Publishers",
    publishedYear: 2014,
    description: "A one-volume commentary by Moody Bible Institute faculty providing verse-by-verse exposition of the entire Bible, written from a conservative evangelical perspective for pastors and serious students.",
    history: "Published by Moody Publishers in 2014, this comprehensive single-volume commentary was written by faculty of Moody Bible Institute and Moody Theological Seminary. It reflects conservative evangelical scholarship across all 66 books, making it a reliable reference for expository preaching and study.",
    canonRating: 9,
    canonNotes: "Commentary covering the complete 66-book Protestant canon from a conservative evangelical perspective.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "The Moody Bible Commentary.pdf",
  },
  {
    title: "The New Unger's Bible Handbook",
    slug: "the-new-ungers-bible-handbook",
    translation: "OTHER",
    publisher: "Moody Publishers",
    publishedYear: 1966,
    description: "Merrill Unger's classic survey of every book of the Bible, covering authorship, date, purpose, outline, and key teachings in an accessible reference format for Bible students.",
    history: "Originally published in 1966 by Merrill F. Unger and updated several times, The New Unger's Bible Handbook provides systematic book-by-book introductions and surveys. It remains one of the most useful quick-reference Bible handbooks for students and teachers.",
    canonRating: 9,
    canonNotes: "Handbook covering all 66 books of the Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "The New Unger's Bible Handbook.pdf",
  },
  {
    title: "The Lord's Prayer Bible Study",
    slug: "the-lords-prayer-bible-study",
    translation: "OTHER",
    publisher: null,
    publishedYear: null,
    description: "An in-depth Bible study guide exploring the Lord's Prayer (Matthew 6:9–13), unpacking its petitions, their theological depth, and practical application for personal and corporate prayer.",
    history: "The Lord's Prayer has been the subject of Christian teaching since the earliest church. This study guide draws on the rich tradition of prayer exposition to help modern believers understand and pray Scripture-shaped prayers rooted in Jesus' own model.",
    canonRating: 9,
    canonNotes: "Study guide based on the standard Protestant canon text. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "The Lord's Prayer Bible Study.pdf",
  },
  {
    title: "Bible and Breakfast",
    slug: "bible-and-breakfast",
    translation: "OTHER",
    publisher: null,
    publishedYear: null,
    description: "A daily devotional companion for morning Bible reading, offering short Scripture readings and reflections to start each day centered on God's Word over breakfast.",
    history: "Daily devotional Bible resources emerged from the 19th-century practice of morning family prayers and Scripture reading. Bible and Breakfast adapts this tradition for modern readers seeking a simple, consistent morning rhythm of Scripture and reflection.",
    canonRating: 9,
    canonNotes: "Devotional resource based on the standard Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "Bible and Breakfast.pdf",
  },
  {
    title: "Couples of the Bible",
    slug: "couples-of-the-bible",
    translation: "OTHER",
    publisher: null,
    publishedYear: null,
    description: "A devotional or study guide examining the marriages and relationships of biblical couples, drawing lessons for contemporary husbands and wives from Adam and Eve to Aquila and Priscilla.",
    history: "Studies of biblical marriages have long been used in pre-marital and marriage enrichment ministry. This resource applies the stories of Scripture's couples to modern relationship challenges, using biblical narrative as a mirror for healthy Christian marriage.",
    canonRating: 9,
    canonNotes: "Study resource based on the standard Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "Couples of the Bible.pdf",
  },
  {
    title: "Learn the Bible in 24 Hours",
    slug: "learn-the-bible-in-24-hours",
    translation: "OTHER",
    publisher: "Thomas Nelson",
    publishedYear: 2002,
    description: "Chuck Missler's systematic survey of the entire Bible in 24 one-hour segments, presenting each book's content, themes, and prophetic significance in an accessible lecture format.",
    history: "Chuck Missler (1934–2018), a Bible teacher known for his technical background and prophetic focus, developed this 24-hour curriculum for Koinonia House. It covers every book of the Bible and became a widely used introduction for serious Bible students worldwide.",
    canonRating: 9,
    canonNotes: "Survey resource covering the complete 66-book Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "Learn the Bible in 24 Hours.pdf",
  },
  {
    title: "Studying, Interpreting, and Applying the Bible",
    slug: "studying-interpreting-applying-the-bible",
    translation: "OTHER",
    publisher: null,
    publishedYear: null,
    description: "A hermeneutics and Bible study methods guide teaching readers how to accurately understand Scripture using principles of observation, interpretation, and application.",
    history: "Bible study methodology has been a formal discipline since the Reformation. This type of resource draws on the tradition of biblical hermeneutics to equip ordinary believers with skills previously reserved for seminary-trained clergy.",
    canonRating: 9,
    canonNotes: "Methods guide applicable to the complete 66-book Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "Studying, Interpreting, and Applying the Bible.pdf",
  },
  {
    title: "Believer's Bible Commentary, 1st Edition",
    slug: "believers-bible-commentary-1st",
    translation: "OTHER",
    publisher: "Thomas Nelson",
    publishedYear: 1989,
    description: "William MacDonald's beloved one-volume commentary covering every chapter of the entire Bible with clear, devotional exposition from a Plymouth Brethren perspective. One of the most comprehensive single-volume Bible commentaries ever produced.",
    history: "William MacDonald (1917–2007) wrote this commentary over many years, first published in 1989 by Thomas Nelson. Known for its clarity, warmth, and devotional insight, it became one of the best-selling Bible commentaries ever, reflecting MacDonald's Plymouth Brethren theology and passion for discipleship.",
    canonRating: 9,
    canonNotes: "Commentary covering all 66 books of the Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: true, filename: "Believer's Bible Commentary, 1st Edition.pdf",
  },
  {
    title: "Believer's Bible Commentary, 2nd Edition",
    slug: "believers-bible-commentary-2nd",
    translation: "OTHER",
    publisher: "Thomas Nelson",
    publishedYear: 2016,
    description: "The updated second edition of William MacDonald's classic one-volume commentary, revised and expanded with updated cross-references and corrected typographical errors throughout.",
    history: "The second edition of the Believer's Bible Commentary (2016) updated MacDonald's original 1989 work with minor corrections and improvements while preserving the beloved character of his exposition. It remains the most comprehensive single-volume commentary available.",
    canonRating: 9,
    canonNotes: "Commentary covering all 66 books of the Protestant canon. Not a translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "Believer's Bible Commentary, 2nd Edition.pdf",
  },
  {
    title: "Battlefield of the Mind Bible",
    slug: "battlefield-of-the-mind-bible",
    translation: "AMP",
    publisher: "FaithWords / Joyce Meyer Ministries",
    publishedYear: 2015,
    description: "Joyce Meyer's Battlefield of the Mind teaching woven throughout the Amplified Bible text, connecting Meyer's insights on thought patterns, renewing the mind, and mental strongholds directly to Scripture.",
    history: "Joyce Meyer's 'Battlefield of the Mind' (1995) became one of the best-selling Christian books of all time. This Bible edition embeds her teaching themes — particularly about thinking patterns and spiritual warfare — throughout the Amplified text, combining Scripture with Meyer's practical insights.",
    canonRating: 9,
    canonNotes: "Uses the Amplified Bible text — 66-book Protestant canon with amplified notation.",
    gradientFrom: "#0F1E40", gradientTo: "#070F1F", accentColor: "#E8CC4A",
    featured: false, filename: "Battlefield of the Mind Bible.pdf",
  },
  {
    title: "Bible, Goodspeed — The Junior Bible",
    slug: "bible-goodspeed-junior",
    translation: "GOODSPEED",
    publisher: "University of Chicago Press",
    publishedYear: 1936,
    description: "Edgar J. Goodspeed's translation presented in a junior edition for young readers, featuring the clear American English of his landmark early-modern translation adapted for accessibility.",
    history: "Edgar J. Goodspeed (1871–1962) was a pioneering NT scholar at the University of Chicago who produced the first major American colloquial translation of the NT (1923) and later the complete Bible with J.M.P. Smith (1931). The Junior Bible adapted this translation for younger audiences.",
    canonRating: 9,
    canonNotes: "Based on the standard 66-book Protestant canon with dynamic equivalence translation philosophy.",
    gradientFrom: "#2A2A1E", gradientTo: "#141410", accentColor: "#C8C870",
    featured: false, filename: "Bible, Goodspeed, The Junior Bi - Bible.pdf",
  },
  {
    title: "The OSNOVA Study Bible",
    slug: "osnova-study-bible",
    translation: "OTHER",
    publisher: null,
    publishedYear: null,
    description: "The OSNOVA Study Bible is a structured study resource providing systematic theological notes and foundational biblical teaching across the full scope of Scripture.",
    history: "OSNOVA (Russian for 'foundation') represents a study resource providing foundational biblical instruction, likely designed for Eastern European or Russian-language ministry contexts. It draws from sound evangelical scholarship.",
    canonRating: 9,
    canonNotes: "Study resource based on the standard Protestant canon. Not a primary English translation.",
    gradientFrom: "#1E1E2A", gradientTo: "#0F0F14", accentColor: "#7B6EF8",
    featured: false, filename: "Bible, OSNOVA Study Bible - Bible.pdf",
  },
  {
    title: "NAB Little Rock Catholic Bible",
    slug: "nab-little-rock-catholic",
    translation: "NAB",
    publisher: "Liturgical Press / Little Rock Scripture Study",
    publishedYear: 1998,
    description: "The Little Rock Catholic Bible uses the New American Bible text with study notes developed by Little Rock Scripture Study, a widely used Catholic Bible study program offering pastoral formation resources.",
    history: "Little Rock Scripture Study was founded in 1974 in the Diocese of Little Rock, Arkansas, providing accessible Catholic Bible study programs for parishes. This Bible edition pairs the official US Catholic NAB translation with their distinctive study helps for group and personal study.",
    canonRating: 5,
    canonNotes: "Uses the Catholic NAB canon of 73 books including deuterocanonicals. Not aligned with the 66-book Protestant canon.",
    gradientFrom: "#1A0F3A", gradientTo: "#0D0820", accentColor: "#C9A84C",
    featured: false, filename: "Bible, NAB, Little Rock Catholi - Bible.pdf",
  },
  {
    title: "NRSV HarperCollins Study Bible (Alt. Ed.)",
    slug: "nrsv-harpercollins-study-alt",
    translation: "NRSV",
    publisher: "HarperOne / Society of Biblical Literature",
    publishedYear: 1993,
    description: "An alternate edition of the authoritative HarperCollins Study Bible, featuring the complete NRSV text with SBL scholarly annotations for academic and serious study.",
    history: "The HarperCollins Study Bible has been the standard academic study Bible since its first edition in 1993, produced in partnership with the Society of Biblical Literature. This edition carries the NRSV text with notes reflecting the best of mainstream biblical scholarship.",
    canonRating: 6,
    canonNotes: "Includes the Apocrypha alongside the 66-book Protestant canon in many editions. Strong scholarly credentials.",
    gradientFrom: "#2B1E10", gradientTo: "#150F08", accentColor: "#C9A87E",
    featured: false, filename: "Bible, The HarperCollins Study - Bible.pdf",
  },
];
