/**
 * sync-images-to-prod.ts
 *
 * After generate-lesson-images.ts has finished locally,
 * this script syncs lesson content (with embedded images) to production.
 *
 * Steps:
 *   1. Reads all local lessons that contain image markdown
 *   2. Writes a SQL file to /tmp/sync-lesson-images.sql
 *   3. rsync + SSH to apply it on the production server
 *
 * Run:
 *   pnpm tsx --env-file=.env.local scripts/sync-images-to-prod.ts
 */

import { PrismaClient } from "@prisma/client";
import { execSync } from "child_process";
import * as fs from "fs";

const db = new PrismaClient();

const PROD_HOST = "web";                     // SSH alias
const PROD_DB_CONTAINER = "godstruth_postgres";
const PROD_DB_USER = "multipledevsites1";
const PROD_DB_NAME = "godstruth";
const SQL_FILE = "/tmp/sync-lesson-images.sql";

function escapeSql(s: string): string {
  // Use dollar-quoting with a unique tag.
  // Replace any stray $body$ occurrences in content (extremely unlikely).
  return s.replace(/\$body\$/g, "\\$body\\$");
}

async function main() {
  const lessons = await db.courseLesson.findMany({
    where: { content: { contains: "![" } },
    select: { title: true, content: true },
    orderBy: { order: "asc" },
  });

  console.log(`Found ${lessons.length} lessons with images to sync.`);

  const lines: string[] = [
    "-- Generated by sync-images-to-prod.ts",
    "BEGIN;",
    "",
  ];

  for (const l of lessons) {
    const safetitle = l.title!.replace(/'/g, "''");
    const safeContent = escapeSql(l.content!);
    lines.push(`UPDATE "CourseLesson"`);
    lines.push(`  SET "content" = $body$${safeContent}$body$`);
    lines.push(`  WHERE "title" = '${safetitle}';`);
    lines.push("");
  }

  lines.push("COMMIT;");
  fs.writeFileSync(SQL_FILE, lines.join("\n"), "utf8");
  console.log(`✅  SQL written to ${SQL_FILE} (${(fs.statSync(SQL_FILE).size / 1024).toFixed(1)} KB)`);

  // rsync SQL file to production /tmp
  console.log("\nrsyncing SQL to production…");
  execSync(`rsync -az ${SQL_FILE} ${PROD_HOST}:/tmp/sync-lesson-images.sql`, { stdio: "inherit" });

  // Apply on production
  console.log("Applying SQL on production DB…");
  execSync(
    `ssh ${PROD_HOST} "docker exec -i ${PROD_DB_CONTAINER} psql -U ${PROD_DB_USER} -d ${PROD_DB_NAME} < /tmp/sync-lesson-images.sql"`,
    { stdio: "inherit" }
  );

  console.log("\n✅  Production DB updated with lesson images.");

  // Optionally restart PM2 to clear any caches
  console.log("Restarting PM2 on production…");
  execSync(`ssh ${PROD_HOST} "pm2 reload godstruth"`, { stdio: "inherit" });

  await db.$disconnect();
}

main().catch(async (e) => {
  console.error(e);
  await db.$disconnect();
  process.exit(1);
});
